# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  name: demo
  demands: java

variables:
  # JAVA_HOME: '/usr/lib/jvm/zulu-8-azure-amd64'  # Adjust Java version and path as needed
  ANDROID_HOME: '/Users/mayanksharma/Library/Android/sdk/'
  SDK: '/Users/mayanksharma/Library/Android/sdk'



steps:

- task: CmdLine@2
  displayName: Installing dependencies
  inputs:
    script: |
      echo installing dependencies.....     
      npm install

# - task: CmdLine@2
#   displayName: Gradle build
#   inputs:
#     script: |
#       cd android/
#       ./gradlew clean assembleDebu

- task: Gradle@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean assembleDebug'


# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     packageApp: true
#     workingDirectory: '$(System.DefaultWorkingDirectory)/ios'

- task: Xcode@5
  inputs:
    actions: 'build'
    xcWorkspacePath: 'ios/*.xcodeproj/project.xcworkspace'
    packageApp: true

# - task: CopyFiles@2
#   displayName: 'Copy file to Artifact Staging Directory'
#   inputs:
#     SourceFolder: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/release/'
#     Contents: '**.apk'
#     TargetFolder: '$(Build.artifactStagingDirectory)'
#     OverWrite: true
#     retryCount: '5'




# - task: AppCenterDistribute@3
#   inputs:
#     serverEndpoint: 'app center'
#     appSlug: 'wasanmohit/sample_andorid'
#     appFile: '/Users/mayanksharma/Downloads/testagent/_work/3/a/app-release-unsigned.apk'
#     releaseNotesOption: 'input'
#     releaseNotesInput: 'test'
#     destinationType: 'groups'
